/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBodaRouteImport } from './routes/admin.boda'
import { Route as AdminCuentaRouteImport } from './routes/admin.cuenta'
import { Route as AdminEscanerRouteImport } from './routes/admin.escaner'
import { Route as AdminInvitadosRouteImport } from './routes/admin.invitados'
import { Route as AdminMensajeRouteImport } from './routes/admin.mensaje'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBodaRoute = AdminBodaRouteImport.update({
  id: '/boda',
  path: '/boda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuentaRoute = AdminCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEscanerRoute = AdminEscanerRouteImport.update({
  id: '/escaner',
  path: '/escaner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitadosRoute = AdminInvitadosRouteImport.update({
  id: '/invitados',
  path: '/invitados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensajeRoute = AdminMensajeRouteImport.update({
  id: '/mensaje',
  path: '/mensaje',
  getParentRoute: () => AdminRoute,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/boda': typeof AdminBodaRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/escaner': typeof AdminEscanerRoute
  '/admin/invitados': typeof AdminInvitadosRoute
  '/admin/mensaje': typeof AdminMensajeRoute
  '/i/$token': typeof ITokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/boda': typeof AdminBodaRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/escaner': typeof AdminEscanerRoute
  '/admin/invitados': typeof AdminInvitadosRoute
  '/admin/mensaje': typeof AdminMensajeRoute
  '/i/$token': typeof ITokenRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/boda': typeof AdminBodaRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/escaner': typeof AdminEscanerRoute
  '/admin/invitados': typeof AdminInvitadosRoute
  '/admin/mensaje': typeof AdminMensajeRoute
  '/i/$token': typeof ITokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/boda'
    | '/admin/cuenta'
    | '/admin/escaner'
    | '/admin/invitados'
    | '/admin/mensaje'
    | '/i/$token'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/boda'
    | '/admin/cuenta'
    | '/admin/escaner'
    | '/admin/invitados'
    | '/admin/mensaje'
    | '/i/$token'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/boda'
    | '/admin/cuenta'
    | '/admin/escaner'
    | '/admin/invitados'
    | '/admin/mensaje'
    | '/i/$token'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ITokenRoute: typeof ITokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/boda': {
      id: '/admin/boda'
      path: '/boda'
      fullPath: '/admin/boda'
      preLoaderRoute: typeof AdminBodaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuenta': {
      id: '/admin/cuenta'
      path: '/cuenta'
      fullPath: '/admin/cuenta'
      preLoaderRoute: typeof AdminCuentaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/escaner': {
      id: '/admin/escaner'
      path: '/escaner'
      fullPath: '/admin/escaner'
      preLoaderRoute: typeof AdminEscanerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitados': {
      id: '/admin/invitados'
      path: '/invitados'
      fullPath: '/admin/invitados'
      preLoaderRoute: typeof AdminInvitadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensaje': {
      id: '/admin/mensaje'
      path: '/mensaje'
      fullPath: '/admin/mensaje'
      preLoaderRoute: typeof AdminMensajeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBodaRoute: typeof AdminBodaRoute
  AdminCuentaRoute: typeof AdminCuentaRoute
  AdminEscanerRoute: typeof AdminEscanerRoute
  AdminInvitadosRoute: typeof AdminInvitadosRoute
  AdminMensajeRoute: typeof AdminMensajeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBodaRoute: AdminBodaRoute,
  AdminCuentaRoute: AdminCuentaRoute,
  AdminEscanerRoute: AdminEscanerRoute,
  AdminInvitadosRoute: AdminInvitadosRoute,
  AdminMensajeRoute: AdminMensajeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ITokenRoute: ITokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
